### ISSUE TITLE
502 error when going to review and submit my comments

### ISSUE THREAD

**Issue by konklone** [18F/epa-notice#434]
After writing and saving a comment on Section IX.A (which included some minimal text, plus a PNG attachment [one of the screenshots from an earlier ticket]), I noticed the `Review and Submit` button on the right-hand sidebar:

![screenshot from 2016-07-03 19-31-02](https://cloud.githubusercontent.com/assets/4592/16548205/f967a44a-4154-11e6-92fc-d97680538f1d.png)

I clicked it, and then after some waiting, I got this:

![screenshot from 2016-07-03 19-33-44](https://cloud.githubusercontent.com/assets/4592/16548209/12a479ba-4155-11e6-8ac2-11fb8c467a4a.png)

**Comment by cmc333333** [comment]
regs.gov is down this weekend -- I'm guessing we're blocking while trying to retrieve data from it. We need to add a timeout to that request and treat it like an error state. The app knows how to deal with reg.gov errors, but apparently not timeouts.

**Comment by cmc333333** [comment]
For reference, regs.gov is now up, so this page should work again. eregs/regulations-site#445 should fix it more permanently
